query GetAvailableRooms($queryParams: RoomWhiteLabelQueryDto!) {
  getRooms(queryParams: $queryParams) {
    meta {
      ...MetaFragment
    }
    items {
      id
      location {
        district
        minPrice
      }
      roomType {
        name
      }
    }
  }
}
