query GetLocationOptions($queryParams: LocationWhiteLabelQueryDto!) {
  getLocations(queryParams: $queryParams) {
    meta {
      ...MetaFragment
    }
    items {
      id
      name
      thumbnail
      gallery
      address
    }
  }
}
