query GetLocation($id: String!, $coordinates: GeoLocationDto) {
  getLocation(id: $id, coordinates: $coordinates) {
    id
    name
    phoneContact
    emailContact
    address
    gallery
    thumbnail
    geoLocation
    description
    serviceReferenceIds
    amenityIds
    minPrice
    maxPrice
    country
    city
    district
    coordinates {
      longitude
      latitude
      distance
    }
    establishedAt
    status
    createdAt
  }
}
