query GetSearchLocations($queryParams: LocationWhiteLabelQueryDto!) {
  getLocations(queryParams: $queryParams) {
    meta {
      ...MetaFragment
    }
    items {
      id
      name
      address
      thumbnail
      rating
      minPrice
      maxPrice
      gallery
      numOfAvailableRoom
      amenityIds
    }
  }
}
