export const DEFAULT_WEEKLY_CALENDAR_START_TIME = 6;
export const DEFAULT_WEEKLY_CALENDAR_END_TIME = 18;
export const DEFAULT_WEEKLY_HOUR_CELL_HEIGHT = 80;
export const DEFAULT_WEEKLY_COLUMN_WIDTH = 152;
