export enum ApolloService {
  Audit = 'audit',
  Contract = 'contract',
  Customer = 'customer',
  CustomerPublic = 'customerPublic',
  Identity = 'identity',
  Integration = 'integration',
  Maintenance = 'maintenance',
  Notification = 'notification',
  Payment = 'payment',
  Private = 'private',
  Property = 'property',
  Public = 'public',
  Reservation = 'reservation',
  Storage = 'storage',
}
