export enum FileType {
  Avi = 'video/x-msvideo',
  Csv = 'text/csv',
  Doc = 'application/msword',
  Docx = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  Gif = 'image/gif',
  Jpeg = 'image/jpeg',
  Jpg = 'image/jpg',
  Mp3 = 'audio/mpeg',
  Mp4 = 'video/mp4',
  Pdf = 'application/pdf',
  Png = 'image/png',
  Ppt = 'application/vnd.ms-powerpoint',
  Pptx = 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  Rar = 'application/x-rar-compressed',
  Svg = 'image/svg+xml',
  Txt = 'text/plain',
  Webp = 'image/webp',
  Xls = 'application/vnd.ms-excel',
  Xlsx = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  Zip = 'application/zip',
}
