name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [ "staging" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Install Node.js and pnpm
      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify your desired Node.js version
      - name: Install pnpm
        run: npm install --global pnpm@9 # Install pnpm

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Run build and tests
      - name: Build the project
        run: pnpm run build
      - name: Run tests
        run: pnpm test:watch

  Deploy-Preview:
    runs-on: ubuntu-latest
    needs: Build # Ensure Deploy-Preview runs only after Build succeeds
    steps:
      - uses: actions/checkout@v2
      
      # Install Node.js and pnpm
      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Ensure the same Node.js version
      - name: Install pnpm
        run: npm install --global pnpm@9

      # Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # Pull Vercel environment information
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # Build artifacts (optional step since already built in Build job)
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # Deploy project artifacts to Vercel
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
